global:
  email:
    display_name: 'GitLab'
    from: 'gitlab@localhost'
    reply_to: 'noreply@localhost'
  smtp:
    enabled: true
    address: 'localhost'
    tls: false
    authentication: ""
    domain: localhost
  edition: ce
  ingress:
    configureCertmanager: false
    class: ""
  hosts:
    https: false
    domain: 127.0.0.1.nip.io
    externalIP: 127.30.0.1
  shell:
    port: 32022
certmanager:
  install: false
nginx-ingress:
  enabled: false
gitlab:
  gitlab-shell:
    service:
      type: NodePort
      nodePort: 32022
gitlab-runner:
  externalUrl: gitlab-webservice-default:8080
  certsSecretName: gitlab-wildcard-tls-chain
