version: "3"
dotenv:
  - .env
tasks:
  cfg:scripts:
    desc: Configure Scripts to be executable
    cmds:
      - chmod -R +x ./scripts
  getpw:
    desc: Gets GitLab root password
    cmds:
      - kubectl get secret gitlab-gitlab-initial-root-password -ojsonpath='{.data.password}' | base64 --decode ; echo
  start:
    desc: Setup local cluster
    cmds:
      - ./scripts/local/create-k3d-cluster.sh {{.CLI_ARGS}}
      - ./scripts/local/helm-deploy-gitlab.sh
  stop:
    desc: Clears local cluster
    cmds:
      - ./scripts/local/delete-k3d-cluster.sh {{.CLI_ARGS}}

  apply:
    desc: Apply the cluster with Terraform
    cmds:
      - terraform init
      - terraform apply
      - task: info
  info:
    desc: Show GitLab information
    cmds:
      - "echo GitLab URL: $(terraform output -json | jq .gitlab_address.value) && echo Root Password: $(terraform output -json | jq .initial_secret.value.password)"

  destroy:
    desc: Destroy the cluster with Terraform
    cmds:
      - terraform destroy

  lint:
    desc: Lints all important files
    cmds:
      - task: lint:sh

  lint:sh:
    desc: Lints shell scripts
    cmds:
      - for file in $(find . -type f -name "*.sh"); do shellcheck $file; done;

  fmt:
    desc: Run all formatting supported.
    ignore_error: true
    summary: |
      Runs all formatting supported.
      1. Runs fmt:md, which formats all Markdown using prettier
      2. Runs fmt:yaml, which formats all YAML using prettier
      3. Runs fmt:nix, which formats all Nix files with nixpkgs-fmt
      4. Runs fmt:sh, which format all sh files with shfmt
    cmds:
      - task: fmt:md
      - task: fmt:yaml
      - task: fmt:nix
      - task: fmt:sh

  fmt:sh:
    desc: Formats shell scripts with shfmt
    cmds:
      - shfmt -w .
  fmt:md:
    ignore_error: true
    desc: Formats Markdown with prettier
    cmds:
      - prettier -w "**/*.MD"
  fmt:yaml:
    ignore_error: true
    desc: Formats YAML with prettier
    cmds:
      - prettier -w "**/*.yaml"
      - prettier -w "**/*.yml"
  fmt:nix:
    ignore_error: true
    desc: Formats Nix files
    cmds:
      - nixpkgs-fmt .
